name = "ON Modded"
author = "cute_panda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8094f96d588ef09859bf42129650465859671efbf788a592ed25a7772e8194a4"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
